name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7
        with:
          toolchain: nightly,stable
          components: rustfmt,clippy

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check for typos
        uses: crate-ci/typos@7c572958218557a3272c2d6719629443b5cc26fd
        with:
          config: ./typos.toml

      - name: Lint
        run: cargo clippy

      - name: Build
        run: cargo build --all-targets --all-features

      - name: Install just
        uses: taiki-e/install-action@cf525cb33f51aca27cd6fa02034117ab963ff9f1
        with:
          tool: just

      - name: Run tests
        run: just test
